<a href="https://colab.research.google.com/github/sakipatsu/Rabbit_Challenge/blob/main/%E5%BF%9C%E7%94%A8%E6%95%B0%E5%AD%A6_%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 第一章　　線形代数
## スカラーとベクトルの違い
### スカラー
*   ただ一つの数
*   四則演算が可能
*.  ベクトルに対する係数になれる

### ベクトル
*   「大きさ」と「向き」を持つ
*   矢印で図示される
*.  スカラーのセットで表示される

## 行列
二次元的に並んだ数字
行数n　、列数mの行列をn✖️mの行列と呼ぶ。

### 行列の積
行列の積は連立方程式の中から生まれた。。。らしい。
$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\quad
\begin{pmatrix}
e \\
f \\
\end{pmatrix} =
\begin{pmatrix}
a * e + b * f \\
c * e + d * f \\
\end{pmatrix}
$$

###逆行列の求め方
掃き出し法
* 左辺に逆行列変換した行列を並べる。
* 右辺に単位行列を並べる。
* 左右の係数の行列に同じ行基本変形を実行したと考える。
* 左辺を単位行列になるように式変形を行う。
* 右辺に逆行列が求まる。

注意：逆行列が存在しない条件

$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
$$

上記のような行列があった時、
以下の関係が成り立つ場合は、逆行列を持つ。
$$a : b \neq c : d　$$
一方で、以下の場合は、逆行列を持たない。
$$a : b = c : d　$$

## 固有値・固有ベクトル
ある行列Aに対し、以下のような式が成り立つような特殊ベクトルxと、右辺の係数λがある。
Ax=λx
特殊なベクトルxとその係数λを、行列Aに対する、固有ベクトル、固有値という。

固有値・固有ベクトルを用いた、特異値分解ではある行列を扱いやすい形式の3つの行列積に分解する。

ある行列X（n行 m列） \\
n ・・・ データの数 \\
m ・・・ 属性の数/特徴量の数 \\

$X = U \cdot D \cdot V^\mathrm{T} $

$U$ ・・・ 左特異ベクトル n行/r列 \\
$D$ ・・・ r行/r列 \\
$V^\mathrm{T}$ ・・・ 右特異ベクトル r行/m列 ※主成分ベクトル


In [7]:
import numpy as np
import numpy.linalg as LA

#問題1-1-8-4をPythonで計算してみる
#ある行列 Xを設定
X = np.array([[3, 2, 0],
              [0, 2, 0],
              [0, 0, 1]])

# 2 次正方行列 Aの固有値、固有ベクトルPを計算する
l, U = LA.eig(X)
print("固有値")
print(l)  # 固有値
print("固有ベクトル P ")
print(U)  # 固有ベクトル(正規化済)

#対角行列D、Pの逆行列P-1を定義
D = np.array([[l[0],0, 0],
              [0,l[1],0],
              [0, 0, l[2]]])
print("D")
print(D)
VT = LA.inv(U)
print("VT")
print(VT)

#固有値分解の確認(U＊D＊VT） 行列Xの逆算ができる
print("固有値分解 確認 X = U x D x VT")
print(np.dot(np.dot(U,D),VT))

固有値
[3. 2. 1.]
固有ベクトル P 
[[ 1.         -0.89442719  0.        ]
 [ 0.          0.4472136   0.        ]
 [ 0.          0.          1.        ]]
D
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]
VT
[[1.         2.         0.        ]
 [0.         2.23606798 0.        ]
 [0.         0.         1.        ]]
固有値分解 確認 X = U x D x VT
[[3. 2. 0.]
 [0. 2. 0.]
 [0. 0. 1.]]


# 第二章　確率・統計
## 集合とは
ものの集まり \\
$ S = \{ a,b,c,d,e,f,g \}$ \\
$ M = \{ c,d,g \}$ \\
$ N = \{ h,i,j \}$ \\
上記の集合があった場合、下記のように表現することができる \\
$ M \in S$ \\
$ N \notin S$ \\

## 和集合と共通部分

$ A \cup B $ AとBの和集合 \\
$ A \cap B $ AとBの共通部分 \\
$ U \setminus A = \overline{A}$ 全体（U)からAを取り除いた集合。差集合\\

# 確率
## 頻度確率（客観確率）
*   発生する頻度

## ベイズ確率（主観確率）
*   信念の度合い

## 確率の定義
$ \mathcal{P}(A) = \frac{事象Aが起こる数}{すべての事象の数} $ \\
$ \overline{A} = 1 - \mathcal{P}(A)  $ \\

## 条件付きの確率
$ \mathcal{P}(A|B) = \frac{ \mathcal{P}(A \cap B)}{\mathcal{P}(B)} $ \\

## 独立な事象の同時確立
$ \mathcal{P}(A \cap B) = \mathcal{P}(A) \mathcal{P}(B|A) $ \\

## ベイズ則
ベイズ則は原因の確率を導くために用いられる。
$ \mathcal{P}(A) \mathcal{P}(B|A) = \mathcal{P}(B) \mathcal{P}(A|B) $ \\

## ヘイズ則を利用した問題を考える。
• ある街の⼦どもたちは毎⽇1/4の確率で飴⽟をもらうことができ，飴⽟をもらうと1/2の確率で笑顔になるという。その街の，笑顔な⼦どもが飴⽟をもらっている確率を求めよ。(ただし，この街の⼦どもたちが笑顔でいる確率は1/3である。)

上記文章より、書く確率は下記で表せる。
$P(飴玉)= \frac{1}{4}$ \\
$P(笑顔|飴玉)= \frac{1}{2}$ \\
$P(笑顔)= \frac{1}{3}$ \\

上記確率がわかっている場合に、笑顔な子供が飴玉をもらっている確率$P(飴玉|笑顔)$は
$P(飴玉|笑顔)=\frac{P(笑顔|飴玉) \cdot P(飴玉)}{P(笑顔)}$ \\
$P(飴玉|笑顔)=\frac{\frac{1}{2} \cdot \frac{1}{4}}{\frac{1}{3}}$ \\
$P(飴玉|笑顔)=\frac{3}{8}$

このようにベイズ則を用いることで確率表現することができる。

# 第三章　情報理論
## 自己情報量
珍しい事象（確率が低い）ほど、情報量は大きい。
複数の事象が起こる確率は積で計算されるが情報量は和で計算。
* 対数の底が2のとき，単位はビット(bit)
* 対数の底がネイピアのeのとき，単位は(nat) \\
$ I(x)=-\log (P(x)) = \log (W(x)) $

## シャノンエントロピーの定義
事象の起こる確率は積で計算されるが、情報量は和で計算可能な量となる。
しかし、事象の起こりやすさは同じではなく、それぞれ固有の起こりやすさがある。
そこで、平均情報量と呼ばれる事象の起こりにくさで重み付けを行った上でたしあわせを行う。
* 微分エントロピーともいう(注意：微分しているわけではない)
* 自己情報量の期待値 \\
$𝐻(𝑥) = 𝐸(𝐼(𝑥)) = −𝐸 ( \log (𝑃(𝑥))) = −∑ (𝑃(𝑥) \log (𝑃(𝑥)))$

## KLダイバージェンス
* 同じ事象・確率変数における異なる確率分布P,Qの違いを表す \\
⇨ 二つの確率分布を比較 \\
$ D_{P||Q} = \sum \limits_{x} P(x) logi \frac{P(x)}{Q(x)} $

## 交差エントロピー
* KLダイバージェンスの一部分を取り出したもの
* Qについての自己情報量をPの分布で平均している